---
- name: Configure standard ACL
  hosts: R1
  gather_facts: false
  connection: network_cli
 
  tasks:
   - name: Load new ACL into device
     ios_config:
       parents: ip access-list extended REQ3
       lines:
         - 10 permit tcp host 192.168.20.20 host 192.168.10.10 eq www
         - 20 deny tcp any any eq www
         - 30 permit ip any any
                  
   - name: Apply new ACL to R1 Eth0/0.10 out
     ios_config:
       parents: int e0/0.10
       lines:
         - ip access-group REQ3 out

   - name: Check result
     ios_command:
       commands: sh run
     register: result
     tags: show

   - name: Print result
     debug:
       var: result.stdout_lines
     tags: show
